# Generated by Django 4.2.11 on 2024-05-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], default=True, max_length=50),
        ),
    ]
